-- ============================================================================
-- NutriTrack Database Schema
-- Generated from Hibernate JPA Entities (Spring Boot 3.5.7 + Hibernate 6.6.33)
-- Compatible with PostgreSQL 16.10
-- All IDs use BIGINT with auto-increment (GENERATED BY DEFAULT AS IDENTITY)
-- Last Updated: December 1, 2025
-- ============================================================================

-- ============================================================================
-- DROP EXISTING TABLES (in correct order for foreign keys)
-- ============================================================================

DROP TABLE IF EXISTS registros_ejercicios CASCADE;
DROP TABLE IF EXISTS registros_comidas CASCADE;
DROP TABLE IF EXISTS usuarios_rutinas CASCADE;
DROP TABLE IF EXISTS usuarios_planes CASCADE;
DROP TABLE IF EXISTS rutina_etiquetas CASCADE;
DROP TABLE IF EXISTS rutina_ejercicios CASCADE;
DROP TABLE IF EXISTS rutinas CASCADE;
DROP TABLE IF EXISTS plan_etiquetas CASCADE;
DROP TABLE IF EXISTS plan_dias CASCADE;
DROP TABLE IF EXISTS plan_objetivos CASCADE;
DROP TABLE IF EXISTS planes CASCADE;
DROP TABLE IF EXISTS recetas CASCADE;
DROP TABLE IF EXISTS comida_etiquetas CASCADE;
DROP TABLE IF EXISTS comida_ingredientes CASCADE;
DROP TABLE IF EXISTS comidas CASCADE;
DROP TABLE IF EXISTS tipos_comida CASCADE;
DROP TABLE IF EXISTS ingrediente_etiquetas CASCADE;
DROP TABLE IF EXISTS ingredientes CASCADE;
DROP TABLE IF EXISTS ejercicio_etiquetas CASCADE;
DROP TABLE IF EXISTS ejercicios CASCADE;
DROP TABLE IF EXISTS usuario_etiquetas_salud CASCADE;
DROP TABLE IF EXISTS etiquetas CASCADE;
DROP TABLE IF EXISTS usuario_historial_medidas CASCADE;
DROP TABLE IF EXISTS usuario_perfil_salud CASCADE;
DROP TABLE IF EXISTS perfiles_usuario CASCADE;
DROP TABLE IF EXISTS cuentas_auth CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- ============================================================================
-- CORE TABLES: Authentication & User Profiles
-- ============================================================================

-- Roles table
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_rol VARCHAR(255) NOT NULL UNIQUE CHECK (tipo_rol IN ('ROLE_USER', 'ROLE_ADMIN'))
);

-- Authentication accounts table
CREATE TABLE cuentas_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATE NOT NULL DEFAULT CURRENT_DATE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    id_rol BIGINT,
    CONSTRAINT fk_cuentas_auth_rol FOREIGN KEY (id_rol) REFERENCES roles(id)
);

-- User profiles table
CREATE TABLE perfiles_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_inicio_app DATE NOT NULL DEFAULT CURRENT_DATE,
    id_usuario BIGINT NOT NULL UNIQUE,
    unidades_medida VARCHAR(10) CHECK (unidades_medida IN ('KG', 'LBS')),
    apellido VARCHAR(100) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT fk_perfiles_usuario_cuenta FOREIGN KEY (id_usuario) REFERENCES cuentas_auth(id)
);

-- User health profile table (1-to-1 with perfiles_usuario)
CREATE TABLE usuario_perfil_salud (
    id_perfil BIGINT PRIMARY KEY,
    fecha_actualizacion DATE NOT NULL DEFAULT CURRENT_DATE,
    nivel_actividad_actual VARCHAR(255) NOT NULL CHECK (nivel_actividad_actual IN ('BAJO', 'MODERADO', 'ALTO')),
    objetivo_actual VARCHAR(255) NOT NULL CHECK (objetivo_actual IN ('PERDER_PESO', 'GANAR_MASA_MUSCULAR', 'MANTENER_FORMA', 'REHABILITACION', 'CONTROLAR_ESTRES')),
    CONSTRAINT fk_usuario_perfil_salud_perfil FOREIGN KEY (id_perfil) REFERENCES perfiles_usuario(id)
);

-- User measurement history table
CREATE TABLE usuario_historial_medidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    altura NUMERIC(5,2) NOT NULL,
    fecha_medicion DATE NOT NULL DEFAULT CURRENT_DATE,
    imc NUMERIC(5,2),
    peso NUMERIC(5,2) NOT NULL,
    id_cliente BIGINT NOT NULL,
    CONSTRAINT fk_usuario_historial_medidas_cliente FOREIGN KEY (id_cliente) REFERENCES perfiles_usuario(id)
);

-- ============================================================================
-- CONTENT LIBRARY: Tags, Exercises, Ingredients, Meals
-- ============================================================================

-- Tags/Labels table
CREATE TABLE etiquetas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    tipo_etiqueta VARCHAR(50) NOT NULL CHECK (tipo_etiqueta IN ('ALERGIA', 'CONDICION_MEDICA', 'OBJETIVO', 'DIETA', 'DIFICULTAD', 'GRUPO_MUSCULAR', 'TIPO_EJERCICIO')),
    descripcion TEXT,
    nombre VARCHAR(255) NOT NULL UNIQUE
);

-- User health tags (many-to-many)
CREATE TABLE usuario_etiquetas_salud (
    id_etiqueta BIGINT NOT NULL,
    id_perfil BIGINT NOT NULL,
    PRIMARY KEY (id_etiqueta, id_perfil),
    CONSTRAINT fk_usuario_etiquetas_salud_etiqueta FOREIGN KEY (id_etiqueta) REFERENCES etiquetas(id),
    CONSTRAINT fk_usuario_etiquetas_salud_perfil FOREIGN KEY (id_perfil) REFERENCES perfiles_usuario(id)
);

-- Exercises table
CREATE TABLE ejercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    descripcion TEXT,
    tipo_ejercicio VARCHAR(50) NOT NULL CHECK (tipo_ejercicio IN ('CARDIO', 'FUERZA', 'FLEXIBILIDAD', 'EQUILIBRIO', 'HIIT', 'YOGA', 'PILATES', 'FUNCIONAL', 'DEPORTIVO', 'REHABILITACION', 'OTRO')),
    grupo_muscular VARCHAR(50) NOT NULL CHECK (grupo_muscular IN ('PECHO', 'ESPALDA', 'HOMBROS', 'BRAZOS', 'BICEPS', 'TRICEPS', 'ABDOMINALES', 'PIERNAS', 'CUADRICEPS', 'ISQUIOTIBIALES', 'GLUTEOS', 'GEMELOS', 'CORE', 'CARDIO', 'CUERPO_COMPLETO', 'OTRO')),
    nivel_dificultad VARCHAR(50) NOT NULL CHECK (nivel_dificultad IN ('PRINCIPIANTE', 'INTERMEDIO', 'AVANZADO', 'EXPERTO')),
    calorias_quemadas_por_minuto NUMERIC(6,2),
    duracion_estimada_minutos INTEGER,
    equipo_necesario VARCHAR(500),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- Exercise tags (many-to-many)
CREATE TABLE ejercicio_etiquetas (
    id_ejercicio BIGINT NOT NULL,
    id_etiqueta BIGINT NOT NULL,
    PRIMARY KEY (id_ejercicio, id_etiqueta),
    CONSTRAINT fk_ejercicio_etiquetas_etiqueta FOREIGN KEY (id_etiqueta) REFERENCES etiquetas(id),
    CONSTRAINT fk_ejercicio_etiquetas_ejercicio FOREIGN KEY (id_ejercicio) REFERENCES ejercicios(id)
);

-- Ingredients table
CREATE TABLE ingredientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    proteinas NUMERIC(7,2) NOT NULL,
    carbohidratos NUMERIC(7,2) NOT NULL,
    grasas NUMERIC(7,2) NOT NULL,
    energia NUMERIC(7,2) NOT NULL,
    fibra NUMERIC(7,2),
    categoria_alimento VARCHAR(50) NOT NULL CHECK (categoria_alimento IN ('FRUTAS', 'VERDURAS', 'CEREALES', 'LEGUMBRES', 'PROTEINAS', 'LACTEOS', 'GRASAS_SALUDABLES', 'AZUCARES', 'BEBIDAS', 'CONDIMENTOS', 'FRUTOS_SECOS', 'SEMILLAS', 'TUBERCULOS', 'OTRO')),
    descripcion TEXT,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP
);

-- Ingredient tags (many-to-many)
CREATE TABLE ingrediente_etiquetas (
    id_ingrediente BIGINT NOT NULL,
    id_etiqueta BIGINT NOT NULL,
    PRIMARY KEY (id_ingrediente, id_etiqueta),
    CONSTRAINT fk_ingrediente_etiquetas_etiqueta FOREIGN KEY (id_etiqueta) REFERENCES etiquetas(id),
    CONSTRAINT fk_ingrediente_etiquetas_ingrediente FOREIGN KEY (id_ingrediente) REFERENCES ingredientes(id)
);

-- ============================================================================
-- MEAL TYPES TABLE (Dynamic meal type management)
-- ============================================================================

CREATE TABLE tipos_comida (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    descripcion VARCHAR(255),
    orden_visualizacion INTEGER DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert default meal types
INSERT INTO tipos_comida (nombre, descripcion, orden_visualizacion, activo) VALUES
    ('DESAYUNO', 'Primera comida del día', 1, true),
    ('ALMUERZO', 'Comida del mediodía', 2, true),
    ('CENA', 'Última comida principal del día', 3, true),
    ('SNACK', 'Merienda o bocadillo', 4, true),
    ('MERIENDA', 'Comida ligera entre comidas principales', 5, true),
    ('PRE_ENTRENAMIENTO', 'Comida antes del ejercicio', 6, true),
    ('POST_ENTRENAMIENTO', 'Comida después del ejercicio', 7, true),
    ('COLACION', 'Refrigerio ligero', 8, true);

-- ============================================================================
-- MEALS TABLE (References tipos_comida for meal type)
-- ============================================================================

CREATE TABLE comidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    descripcion TEXT,
    instrucciones TEXT,
    porciones INTEGER,
    tiempo_preparacion_minutos INTEGER,
    tiempo_elaboracion INTEGER,
    id_tipo_comida BIGINT,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comidas_tipo_comida FOREIGN KEY (id_tipo_comida) REFERENCES tipos_comida(id)
);

-- Meal-Ingredient relationship (recipes)
CREATE TABLE comida_ingredientes (
    id_comida BIGINT NOT NULL,
    id_ingrediente BIGINT NOT NULL,
    cantidad_gramos NUMERIC(7,2) NOT NULL,
    notas TEXT,
    PRIMARY KEY (id_comida, id_ingrediente),
    CONSTRAINT fk_comida_ingredientes_comida FOREIGN KEY (id_comida) REFERENCES comidas(id),
    CONSTRAINT fk_comida_ingredientes_ingrediente FOREIGN KEY (id_ingrediente) REFERENCES ingredientes(id)
);

-- Meal tags (many-to-many)
CREATE TABLE comida_etiquetas (
    id_comida BIGINT NOT NULL,
    id_etiqueta BIGINT NOT NULL,
    PRIMARY KEY (id_comida, id_etiqueta),
    CONSTRAINT fk_comida_etiquetas_comida FOREIGN KEY (id_comida) REFERENCES comidas(id),
    CONSTRAINT fk_comida_etiquetas_etiqueta FOREIGN KEY (id_etiqueta) REFERENCES etiquetas(id)
);

-- Legacy recipes table (kept for compatibility)
CREATE TABLE recetas (
    id_comida BIGINT NOT NULL,
    id_ingrediente BIGINT NOT NULL,
    cantidad_ingrediente NUMERIC(5,2) NOT NULL,
    PRIMARY KEY (id_comida, id_ingrediente),
    CONSTRAINT fk_recetas_comida FOREIGN KEY (id_comida) REFERENCES comidas(id),
    CONSTRAINT fk_recetas_ingrediente FOREIGN KEY (id_ingrediente) REFERENCES ingredientes(id)
);

-- ============================================================================
-- NUTRITION PLANS MODULE
-- ============================================================================

-- Nutrition plans table
CREATE TABLE planes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    duracion_dias INTEGER NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT
);

-- Plan objectives table (1-to-1 with planes)
CREATE TABLE plan_objetivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calorias_objetivo NUMERIC(10,2),
    carbohidratos_objetivo NUMERIC(10,2),
    grasas_objetivo NUMERIC(10,2),
    proteinas_objetivo NUMERIC(10,2),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    descripcion VARCHAR(500),
    id_plan BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_plan_objetivos_plan FOREIGN KEY (id_plan) REFERENCES planes(id)
);

-- Plan days (meals schedule) - References tipos_comida
CREATE TABLE plan_dias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_dia INTEGER NOT NULL,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    notas VARCHAR(500),
    id_comida BIGINT NOT NULL,
    id_plan BIGINT NOT NULL,
    id_tipo_comida BIGINT,
    CONSTRAINT fk_plan_dias_comida FOREIGN KEY (id_comida) REFERENCES comidas(id),
    CONSTRAINT fk_plan_dias_plan FOREIGN KEY (id_plan) REFERENCES planes(id),
    CONSTRAINT fk_plan_dias_tipo_comida FOREIGN KEY (id_tipo_comida) REFERENCES tipos_comida(id)
);

-- Plan tags (many-to-many)
CREATE TABLE plan_etiquetas (
    id_plan BIGINT NOT NULL,
    id_etiqueta BIGINT NOT NULL,
    PRIMARY KEY (id_plan, id_etiqueta),
    CONSTRAINT fk_plan_etiquetas_etiqueta FOREIGN KEY (id_etiqueta) REFERENCES etiquetas(id),
    CONSTRAINT fk_plan_etiquetas_plan FOREIGN KEY (id_plan) REFERENCES planes(id)
);

-- ============================================================================
-- EXERCISE ROUTINES MODULE (with patron_semanas for weekly patterns)
-- ============================================================================

-- Exercise routines table
CREATE TABLE rutinas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    duracion_semanas INTEGER NOT NULL,
    patron_semanas INTEGER NOT NULL DEFAULT 1,
    nivel_dificultad VARCHAR(50),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    nombre VARCHAR(255) NOT NULL UNIQUE,
    descripcion TEXT,
    CONSTRAINT chk_patron_semanas_positive CHECK (patron_semanas >= 1),
    CONSTRAINT chk_patron_no_excede_duracion CHECK (patron_semanas <= duracion_semanas)
);

-- Routine exercises (with semana_base and dia_semana for scheduling)
CREATE TABLE rutina_ejercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden INTEGER NOT NULL,
    series INTEGER NOT NULL,
    repeticiones INTEGER NOT NULL,
    peso NUMERIC(6,2),
    duracion_minutos INTEGER,
    descanso_segundos INTEGER,
    notas TEXT,
    id_ejercicio BIGINT NOT NULL,
    id_rutina BIGINT NOT NULL,
    semana_base INTEGER NOT NULL DEFAULT 1,
    dia_semana INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT fk_rutina_ejercicios_ejercicio FOREIGN KEY (id_ejercicio) REFERENCES ejercicios(id),
    CONSTRAINT fk_rutina_ejercicios_rutina FOREIGN KEY (id_rutina) REFERENCES rutinas(id),
    CONSTRAINT chk_semana_base_positive CHECK (semana_base >= 1),
    CONSTRAINT chk_dia_semana_range CHECK (dia_semana >= 1 AND dia_semana <= 7)
);

-- Routine tags (many-to-many)
CREATE TABLE rutina_etiquetas (
    id_rutina BIGINT NOT NULL,
    id_etiqueta BIGINT NOT NULL,
    PRIMARY KEY (id_rutina, id_etiqueta),
    CONSTRAINT fk_rutina_etiquetas_etiqueta FOREIGN KEY (id_etiqueta) REFERENCES etiquetas(id),
    CONSTRAINT fk_rutina_etiquetas_rutina FOREIGN KEY (id_rutina) REFERENCES rutinas(id)
);

-- ============================================================================
-- USER ASSIGNMENTS: Plans & Routines
-- ============================================================================

-- User assigned plans
CREATE TABLE usuarios_planes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dia_actual INTEGER DEFAULT 1,
    fecha_fin DATE,
    fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'COMPLETADO', 'CANCELADO', 'PAUSADO')),
    notas TEXT,
    id_perfil_usuario BIGINT NOT NULL,
    id_plan BIGINT NOT NULL,
    CONSTRAINT fk_usuarios_planes_perfil FOREIGN KEY (id_perfil_usuario) REFERENCES perfiles_usuario(id),
    CONSTRAINT fk_usuarios_planes_plan FOREIGN KEY (id_plan) REFERENCES planes(id)
);

-- User assigned routines
CREATE TABLE usuarios_rutinas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_fin DATE,
    fecha_inicio DATE NOT NULL DEFAULT CURRENT_DATE,
    semana_actual INTEGER DEFAULT 1,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(20) NOT NULL DEFAULT 'ACTIVO' CHECK (estado IN ('ACTIVO', 'COMPLETADO', 'CANCELADO', 'PAUSADO')),
    notas TEXT,
    id_perfil_usuario BIGINT NOT NULL,
    id_rutina BIGINT NOT NULL,
    CONSTRAINT fk_usuarios_rutinas_perfil FOREIGN KEY (id_perfil_usuario) REFERENCES perfiles_usuario(id),
    CONSTRAINT fk_usuarios_rutinas_rutina FOREIGN KEY (id_rutina) REFERENCES rutinas(id)
);

-- ============================================================================
-- TRACKING MODULE: Meal & Exercise Logs
-- ============================================================================

-- Meal tracking/logging
CREATE TABLE registros_comidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calorias_consumidas NUMERIC(8,2),
    fecha DATE NOT NULL,
    hora TIME(6) NOT NULL,
    porciones NUMERIC(5,2),
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    notas TEXT,
    id_comida BIGINT NOT NULL,
    id_perfil_usuario BIGINT NOT NULL,
    id_usuario_plan BIGINT,
    id_tipo_comida BIGINT,
    CONSTRAINT fk_registros_comidas_comida FOREIGN KEY (id_comida) REFERENCES comidas(id),
    CONSTRAINT fk_registros_comidas_perfil FOREIGN KEY (id_perfil_usuario) REFERENCES perfiles_usuario(id),
    CONSTRAINT fk_registros_comidas_usuario_plan FOREIGN KEY (id_usuario_plan) REFERENCES usuarios_planes(id),
    CONSTRAINT fk_registros_comidas_tipo_comida FOREIGN KEY (id_tipo_comida) REFERENCES tipos_comida(id)
);

-- Exercise tracking/logging
CREATE TABLE registros_ejercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calorias_quemadas NUMERIC(8,2),
    duracion_minutos INTEGER NOT NULL,
    fecha DATE NOT NULL,
    hora TIME(6) NOT NULL,
    peso_utilizado NUMERIC(6,2),
    repeticiones_realizadas INTEGER,
    series_realizadas INTEGER,
    created_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    notas TEXT,
    id_ejercicio BIGINT NOT NULL,
    id_perfil_usuario BIGINT NOT NULL,
    id_usuario_rutina BIGINT,
    CONSTRAINT fk_registros_ejercicios_ejercicio FOREIGN KEY (id_ejercicio) REFERENCES ejercicios(id),
    CONSTRAINT fk_registros_ejercicios_perfil FOREIGN KEY (id_perfil_usuario) REFERENCES perfiles_usuario(id),
    CONSTRAINT fk_registros_ejercicios_usuario_rutina FOREIGN KEY (id_usuario_rutina) REFERENCES usuarios_rutinas(id)
);

-- ============================================================================
-- INDEXES FOR PERFORMANCE OPTIMIZATION
-- ============================================================================

-- Authentication indexes
CREATE INDEX idx_cuentas_email ON cuentas_auth(email);
CREATE INDEX idx_cuentas_active ON cuentas_auth(active);

-- Profile indexes
CREATE INDEX idx_perfil_usuario ON perfiles_usuario(id_usuario);
CREATE INDEX idx_historial_medidas_perfil ON usuario_historial_medidas(id_cliente);
CREATE INDEX idx_historial_medidas_fecha ON usuario_historial_medidas(fecha_medicion);

-- Plan and routine assignment indexes
CREATE INDEX idx_usuarios_planes_perfil ON usuarios_planes(id_perfil_usuario);
CREATE INDEX idx_usuarios_planes_estado ON usuarios_planes(estado);
CREATE INDEX idx_usuarios_planes_fecha_inicio ON usuarios_planes(fecha_inicio);
CREATE INDEX idx_usuarios_rutinas_perfil ON usuarios_rutinas(id_perfil_usuario);
CREATE INDEX idx_usuarios_rutinas_estado ON usuarios_rutinas(estado);
CREATE INDEX idx_usuarios_rutinas_fecha_inicio ON usuarios_rutinas(fecha_inicio);

-- Tracking indexes
CREATE INDEX idx_registros_comidas_perfil ON registros_comidas(id_perfil_usuario);
CREATE INDEX idx_registros_comidas_fecha ON registros_comidas(fecha);
CREATE INDEX idx_registros_comidas_usuario_plan ON registros_comidas(id_usuario_plan);
CREATE INDEX idx_registros_comidas_tipo_comida ON registros_comidas(id_tipo_comida);
CREATE INDEX idx_registros_ejercicios_perfil ON registros_ejercicios(id_perfil_usuario);
CREATE INDEX idx_registros_ejercicios_fecha ON registros_ejercicios(fecha);
CREATE INDEX idx_registros_ejercicios_usuario_rutina ON registros_ejercicios(id_usuario_rutina);

-- Content library indexes
CREATE INDEX idx_etiquetas_tipo ON etiquetas(tipo_etiqueta);
CREATE INDEX idx_etiquetas_nombre ON etiquetas(nombre);
CREATE INDEX idx_ejercicios_tipo ON ejercicios(tipo_ejercicio);
CREATE INDEX idx_ejercicios_nivel_dificultad ON ejercicios(nivel_dificultad);
CREATE INDEX idx_ejercicios_grupo_muscular ON ejercicios(grupo_muscular);
CREATE INDEX idx_ingredientes_categoria ON ingredientes(categoria_alimento);
CREATE INDEX idx_comidas_tipo ON comidas(id_tipo_comida);
CREATE INDEX idx_tipos_comida_activo ON tipos_comida(activo);

-- Routine exercises index for weekly scheduling
CREATE INDEX idx_rutina_ejercicios_semana_dia ON rutina_ejercicios(id_rutina, semana_base, dia_semana, orden);

-- ============================================================================
-- COMMENTS ON TABLES AND COLUMNS
-- ============================================================================

COMMENT ON TABLE roles IS 'User roles (ROLE_USER, ROLE_ADMIN)';
COMMENT ON TABLE cuentas_auth IS 'User authentication accounts';
COMMENT ON TABLE perfiles_usuario IS 'User profile information';
COMMENT ON TABLE usuario_perfil_salud IS 'User health profile (1-to-1 with perfiles_usuario)';
COMMENT ON TABLE usuario_historial_medidas IS 'User measurement history (weight, height, BMI)';
COMMENT ON TABLE etiquetas IS 'Tags/labels for categorization (allergies, goals, difficulty, etc.)';
COMMENT ON TABLE usuario_etiquetas_salud IS 'User health tags (allergies, medical conditions)';
COMMENT ON TABLE ejercicios IS 'Exercise catalog';
COMMENT ON TABLE ingredientes IS 'Ingredient catalog with nutritional information';
COMMENT ON TABLE tipos_comida IS 'Dynamic meal type catalog (DESAYUNO, ALMUERZO, etc.)';
COMMENT ON TABLE comidas IS 'Meal catalog - references tipos_comida for meal type';
COMMENT ON TABLE comida_ingredientes IS 'Meal recipes (meal-ingredient relationships with quantities in grams)';
COMMENT ON TABLE planes IS 'Nutrition plans catalog';
COMMENT ON TABLE plan_objetivos IS 'Nutrition plan objectives (calories, macros)';
COMMENT ON TABLE plan_dias IS 'Daily meal schedule for nutrition plans - references tipos_comida';
COMMENT ON TABLE rutinas IS 'Exercise routines catalog with weekly pattern support';
COMMENT ON TABLE rutina_ejercicios IS 'Exercises in routines with week/day scheduling';
COMMENT ON TABLE usuarios_planes IS 'User assigned nutrition plans';
COMMENT ON TABLE usuarios_rutinas IS 'User assigned exercise routines';
COMMENT ON TABLE registros_comidas IS 'User meal tracking logs - references tipos_comida';
COMMENT ON TABLE registros_ejercicios IS 'User exercise tracking logs';

COMMENT ON COLUMN perfiles_usuario.unidades_medida IS 'User measurement system: KG or LBS';
COMMENT ON COLUMN usuario_perfil_salud.objetivo_actual IS 'Current health goal: PERDER_PESO, GANAR_MASA_MUSCULAR, MANTENER_FORMA, REHABILITACION, CONTROLAR_ESTRES';
COMMENT ON COLUMN usuario_perfil_salud.nivel_actividad_actual IS 'Current activity level: BAJO, MODERADO, ALTO';
COMMENT ON COLUMN tipos_comida.orden_visualizacion IS 'Display order in UI (1=first)';
COMMENT ON COLUMN comidas.id_tipo_comida IS 'Reference to tipos_comida table for meal type';
COMMENT ON COLUMN registros_comidas.id_tipo_comida IS 'Reference to tipos_comida - can differ from comida default type';
COMMENT ON COLUMN registros_comidas.porciones IS 'Number of servings consumed';
COMMENT ON COLUMN registros_ejercicios.peso_utilizado IS 'Weight used during exercise (kg or lbs)';
COMMENT ON COLUMN planes.duracion_dias IS 'Plan duration in days';
COMMENT ON COLUMN rutinas.duracion_semanas IS 'Routine duration in weeks';
COMMENT ON COLUMN rutinas.patron_semanas IS 'Number of unique weeks in routine pattern (cycles after this)';
COMMENT ON COLUMN rutina_ejercicios.semana_base IS 'Week number within pattern (1 to patron_semanas)';
COMMENT ON COLUMN rutina_ejercicios.dia_semana IS 'Day of week (1=Monday to 7=Sunday)';
COMMENT ON COLUMN usuarios_planes.dia_actual IS 'Current day of the plan (1 to duracion_dias)';
COMMENT ON COLUMN usuarios_rutinas.semana_actual IS 'Current week of the routine (1 to duracion_semanas)';

-- ============================================================================
-- INITIAL DATA (ROLES)
-- ============================================================================

INSERT INTO roles (tipo_rol) VALUES
    ('ROLE_USER'),
    ('ROLE_ADMIN')
ON CONFLICT (tipo_rol) DO NOTHING;

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================
